project:
  type: website

website:
  title: "MA12001 Algebra"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Chapter 1: Vectors"
        contents:
          - href: week1.qmd
          - href: week2.qmd
          - href: week3.qmd
      - section: "Chapter 2: Matrices"
      - section: "Chapter 3: Lines, planes and spheres"
      - section: "Chapter 4: Complex numbers"
      - href: links.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true



