project:
  type: website

website:
  title: "MA12001 Algebra"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Chapter 1: Vectors"
        contents:
          - href: week1.qmd
          - href: week2.qmd
          - href: week3.qmd
      - section: "Chapter 2: Matrices"
        contents:
          - href: week4.qmd
          - href: week5.qmd
          - href: week6.qmd
      - section: "Chapter 3: Lines, planes and spheres"
        contents:
          - href: week7.qmd
          - href: week8.qmd
          - text: "Week 9: Spheres"
      - section: "Chapter 4: Complex numbers"
      - href: links.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true



