---
title: "Week 2: General Vectors"
---

::: {.hidden}

 \newcommand{\V}[1]{{\overrightarrow{#1}}}
 \newcommand{\vc}[1]{{\mathbf{#1}}}

::: 

# General vectors
In the previous section, we worked out a set of rules that it makes sense for mathematical operations on displacements to obey. Mathematicians like to work the other way round: start from a list of rules, and see what we can deduce. This is how, for example, you might be introduced to the mathematical idea of groups.

Firstly, let's introduce some notation to make it clear what's a vector and what's not. We use bold lowercase letters for vectors, like $\vc{a}, \vc{b}, \vc{x}$ etc. For scalars, we'll use non-bold letters, and very often we'll use Greek letters like $\alpha, \beta, \lambda$ and $\mu$. We write the magnitude (length) of the vector $\vc{a}$ as $|\vc{a}|$. ^[When writing vectors with pen and paper or on  the board, bold is difficult, but there are various other possibilities and different people like different things. I use an underline. Whatever you choose, it's very helpful to distinguish between vectors and scalars in your handwriting.]

For vectors (specifically a *normed vector space*, but you don't need to know that), the rules are as follows. For any vectors $\vc{a}$, $\vc{b}$ and $\vc{c}$ and any scalars $\lambda$ and $\mu$,

- $\vc{a}+(\vc{b}+\vc{c}) = (\vc{a}+\vc{b})+\vc{c}$: associativity of vector addition.
- $\vc{a}+\vc{b} = \vc{b} + \vc{a}$: commutativity of vector addition.
- $\vc{a}+\vc{0}=\vc{a}$: adding zero does nothing.
- $\vc{a}+(-\vc{a}) = 0$: subtraction works as expected.
- $\lambda(\mu \vc{a}) = (\lambda \mu) \vc{a}$: multiplication by scalars works as expected.
- $\lambda(\vc{a}+\vc{b}) = \lambda\vc{a}+\lambda\vc{b}$: distributivity of scalar multiplication over vector addition.
- $(\lambda+\mu)\vc{a} = \lambda \vc{a} + \mu \vc{a}$: distributivity of scalar multiplication over scalar addition.
- $|\vc{a}|\geq 0$: the magnitude can't be negative
- $|\vc{a}|=0$ if and only if $\vc{a}=\vc{0}$: there is only one vector with magnitude 0.
- $|\lambda\vc{a}| = |\lambda| |\vc{a}|$: multiplying by a scalar just multiplies the magnitude by that amount (removing the minus sign if necessary).
- $|\vc{a}+\vc{b}|\leq |\vc{a}+\vc{b}|$: the triangle inequality.

That's a long list! Try not to memorise these by rote, but instead learn the rules through practicing with example questions. Most of them are very intuitive. The last rule, the triangle inequality, isn't so intuitive to me.

## Unit vectors
A *unit vector* is a vector with magnitude equal to 1. We sometimes use a little hat to denote unit vectors, like $\hat{\vc{a}}$. So $|\hat{\vc{a}}| = 1$.